# Generated by Django 3.2.8 on 2021-11-21 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume_Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_title_detail', models.CharField(max_length=2000)),
                ('resume_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_title', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_title', models.CharField(max_length=100)),
                ('resume_school', models.TextField(blank=True, max_length=1000, null=True)),
                ('resume_career', models.TextField(blank=True, max_length=1000, null=True)),
                ('resume_text', models.TextField(blank=True, max_length=10000, null=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Resume_Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_certificate', models.FileField(blank=True, null=True, upload_to='resume_file/')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='resumeapp.user_resume')),
            ],
        ),
        migrations.CreateModel(
            name='Resume_UniversitySchool_Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_university_major_list', models.CharField(max_length=200)),
                ('resume_university_major_detail', models.CharField(max_length=200)),
                ('resume_university_major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_university_major', to='resumeapp.resume_title')),
            ],
        ),
        migrations.CreateModel(
            name='Resume_UniversitySchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_study_year', models.CharField(max_length=50)),
                ('university_school_name', models.CharField(max_length=50)),
                ('university_field_name', models.CharField(max_length=50)),
                ('university_start_time', models.CharField(max_length=200)),
                ('university_end_time', models.CharField(max_length=200)),
                ('university_study_time', models.CharField(max_length=200)),
                ('university_study_level', models.CharField(max_length=200)),
                ('university_finaltest', models.CharField(max_length=2000)),
                ('resume_university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_university', to='resumeapp.resume_title')),
            ],
        ),
        migrations.CreateModel(
            name='Resume_MiddleSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_school_name', models.CharField(max_length=50)),
                ('middle_field_name', models.CharField(max_length=50)),
                ('middle_start_time', models.CharField(max_length=200)),
                ('middle_end_time', models.CharField(max_length=200)),
                ('resume_middle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_middle', to='resumeapp.resume_title')),
            ],
        ),
        migrations.CreateModel(
            name='Resume_HighSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high_school_name', models.CharField(max_length=50)),
                ('high_field_name', models.CharField(max_length=50)),
                ('high_start_time', models.CharField(max_length=200)),
                ('high_end_time', models.CharField(max_length=200)),
                ('high_major', models.CharField(max_length=200)),
                ('resume_high', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_high', to='resumeapp.resume_title')),
            ],
        ),
        migrations.CreateModel(
            name='Resume_ElementarySchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elementary_school_name', models.CharField(max_length=50)),
                ('elementary_field_name', models.CharField(max_length=50)),
                ('elementary_start_time', models.CharField(max_length=200)),
                ('elementary_end_time', models.CharField(max_length=200)),
                ('resume_elementary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_elementary', to='resumeapp.resume_title')),
            ],
        ),
    ]
