# Generated by Django 3.2.8 on 2021-11-10 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_title', models.CharField(max_length=100)),
                ('resume_school', models.TextField(blank=True, max_length=1000, null=True)),
                ('resume_career', models.TextField(blank=True, max_length=1000, null=True)),
                ('resume_certificate', models.FileField(blank=True, null=True, upload_to='resume_file/')),
                ('resume_text', models.TextField(blank=True, max_length=10000, null=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
