# Generated by Django 3.2.8 on 2022-05-31 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume_elementaryschool',
            name='elementary_school_file',
            field=models.FileField(blank=True, null=True, upload_to='resume_file/'),
        ),
        migrations.AddField(
            model_name='resume_highschool',
            name='high_school_file',
            field=models.FileField(blank=True, null=True, upload_to='resume_file/'),
        ),
        migrations.AddField(
            model_name='resume_middleschool',
            name='middle_school_file',
            field=models.FileField(blank=True, null=True, upload_to='resume_file/'),
        ),
        migrations.AddField(
            model_name='resume_universityschool',
            name='university_school_file',
            field=models.FileField(blank=True, null=True, upload_to='resume_file/'),
        ),
    ]
