# Generated by Django 3.2.8 on 2022-02-04 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resumeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume_title',
            name='resume_like',
        ),
        migrations.CreateModel(
            name='Resume_Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_like_resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_like_resume', to='resumeapp.resume_title')),
                ('resume_like_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_like_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
