# Generated by Django 3.2.8 on 2021-12-25 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume_Hope_Work_Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_hope_work_work1', models.CharField(max_length=200)),
                ('resume_hope_work_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_hope_work_work', to='resumeapp.resume_title')),
            ],
        ),
        migrations.CreateModel(
            name='Resume_Hope_Work_Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_hope_work_field1', models.CharField(max_length=200)),
                ('resume_hope_work_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_hope_work_field', to='resumeapp.resume_title')),
            ],
        ),
        migrations.CreateModel(
            name='Resume_Hope_Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_hope_work_start_time', models.CharField(max_length=200)),
                ('resume_hope_work_end_time', models.CharField(max_length=200)),
                ('resume_hope_work_money', models.CharField(max_length=200)),
                ('resume_hope_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_hope_work', to='resumeapp.resume_title')),
            ],
        ),
    ]
