# Generated by Django 3.2.8 on 2021-11-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume_elementaryschool',
            name='elementary_end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='resume_elementaryschool',
            name='elementary_start_time',
            field=models.DateField(),
        ),
    ]
