# Generated by Django 3.2.8 on 2022-02-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0002_auto_20220204_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume_title',
            name='like_vote',
            field=models.IntegerField(default=0),
        ),
    ]
