# Generated by Django 3.2.8 on 2021-12-10 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0002_resume_career_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume_Self_Introduce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_self_introduce_title', models.CharField(max_length=500)),
                ('resume_self_introduce_text', models.CharField(max_length=3000)),
                ('resume_self_introduce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_self_introduce', to='resumeapp.resume_title')),
            ],
        ),
        migrations.CreateModel(
            name='Resume_Prize_Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_prize_certificate', models.CharField(max_length=500)),
                ('resume_prize_place', models.CharField(max_length=500)),
                ('resume_prize_title', models.CharField(max_length=500)),
                ('resume_prize_date', models.CharField(max_length=500)),
                ('resume_prize_play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_prize_play', to='resumeapp.resume_title')),
            ],
        ),
        migrations.CreateModel(
            name='Resume_Port_Polio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_port_polio_detail', models.FileField(upload_to='')),
                ('resume_port_polio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_port_polio', to='resumeapp.resume_title')),
            ],
        ),
        migrations.CreateModel(
            name='Resume_Out_Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_out_activity', models.CharField(max_length=500)),
                ('resume_out_place', models.CharField(max_length=500)),
                ('resume_out_start_play', models.CharField(max_length=500)),
                ('resume_out_end_play', models.CharField(max_length=500)),
                ('resume_out_play_text', models.CharField(max_length=500)),
                ('resume_out_play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_out_play', to='resumeapp.resume_title')),
            ],
        ),
    ]
