# Generated by Django 3.2.8 on 2022-01-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0002_auto_20220106_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume_title',
            name='resume_open',
            field=models.IntegerField(default=1),
        ),
    ]
