# Generated by Django 3.2.8 on 2022-06-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0002_auto_20220601_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume_career',
            name='resume_company_file',
            field=models.FileField(blank=True, null=True, upload_to='resume_file/'),
        ),
    ]
