# Generated by Django 3.2.8 on 2021-11-20 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0003_auto_20211120_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume_UniversitySchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_school_name', models.CharField(max_length=50)),
                ('university_start_time', models.CharField(max_length=200)),
                ('university_end_time', models.CharField(max_length=200)),
                ('resume_university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_university', to='resumeapp.resume_title')),
            ],
        ),
        migrations.CreateModel(
            name='Resume_MiddleSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_school_name', models.CharField(max_length=50)),
                ('middle_start_time', models.CharField(max_length=200)),
                ('middle_end_time', models.CharField(max_length=200)),
                ('resume_middle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_middle', to='resumeapp.resume_title')),
            ],
        ),
        migrations.CreateModel(
            name='Resume_HighSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high_school_name', models.CharField(max_length=50)),
                ('high_start_time', models.CharField(max_length=200)),
                ('high_end_time', models.CharField(max_length=200)),
                ('resume_high', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_high', to='resumeapp.resume_title')),
            ],
        ),
    ]
