# Generated by Django 3.2.8 on 2022-03-26 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='company_logo',
            field=models.FileField(blank=True, null=True, upload_to='media/company_logo/'),
        ),
    ]
