# Generated by Django 3.2.8 on 2021-10-24 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend', to=settings.AUTH_USER_MODEL)),
                ('friend_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_relation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('friend', 'friend_relation')},
            },
        ),
    ]
