# Generated by Django 3.2.2 on 2022-01-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='company_number',
            field=models.CharField(max_length=200),
        ),
    ]
