# Generated by Django 3.2.8 on 2022-03-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_alter_myuser_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='company_logo',
            field=models.FileField(blank=True, null=True, upload_to='company_logo/'),
        ),
    ]
