# Generated by Django 3.2.8 on 2022-05-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0003_alter_myuser_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='company_paper',
            field=models.FileField(blank=True, null=True, upload_to='company_paper/'),
        ),
    ]
