# Generated by Django 3.2.8 on 2022-01-28 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_detail', models.CharField(max_length=2000)),
                ('message_date', models.DateField(auto_now=True)),
                ('message_Time', models.TimeField(auto_now=True)),
                ('message_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_model', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
