# Generated by Django 3.2.8 on 2022-05-02 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messageapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message_Propose_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_propose_detail', models.TextField()),
                ('message_propose_company_group', models.CharField(max_length=200)),
                ('message_propose_company_name', models.CharField(max_length=200)),
                ('message_propose_company_ceo', models.CharField(max_length=100)),
                ('message_propose_company_logo', models.FileField(blank=True, null=True, upload_to='message/')),
                ('message_propose_company_phone_number', models.CharField(max_length=2000)),
                ('message_propose_date', models.DateField(auto_now=True)),
                ('message_propose_Time', models.TimeField(auto_now=True)),
                ('message_propose_date_time', models.DateTimeField(auto_now=True)),
                ('message_propose_receive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_propose_receive', to=settings.AUTH_USER_MODEL)),
                ('message_propose_send', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_propose_send', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
