# Generated by Django 3.2.8 on 2022-05-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageapp', '0002_message_propose_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_propose_model',
            name='message_propose_resume_title',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
