# Generated by Django 3.2.8 on 2022-01-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageapp', '0002_test_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_resume_model',
            name='message_date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
