# Generated by Django 3.2.8 on 2022-02-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageapp', '0002_auto_20220201_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message_send_model',
            name='message_send_detail',
            field=models.TextField(),
        ),
    ]
