# Generated by Django 3.2.8 on 2022-02-03 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messageapp', '0003_alter_message_send_model_message_send_detail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message_Receive_Model',
        ),
    ]
