# Generated by Django 3.2.8 on 2022-02-03 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_title', models.CharField(max_length=2000)),
                ('board_detail', models.TextField()),
                ('board_date_time', models.DateTimeField(auto_now=True)),
                ('board_file', models.FileField(blank=True, null=True, upload_to='board/')),
                ('board_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
