# Generated by Django 3.2.8 on 2022-02-03 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boardapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board_Gonge_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_gonge_title', models.CharField(max_length=2000)),
                ('board_gonge_detail', models.TextField()),
                ('board_gonge_date_time', models.DateTimeField(auto_now=True)),
                ('board_gonge_file', models.FileField(blank=True, null=True, upload_to='board/')),
                ('board_gonge_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_gonge_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
